# Generated by Django 3.0.7 on 2020-07-05 18:36

import bootcamp.storagemanager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=bootcamp.storagemanager.GoogleCloudStorage(), upload_to='resumes/', verbose_name='Resume'),
        ),
    ]
