# Generated by Django 3.0.7 on 2020-07-05 19:11

import bootcamp.storagemanager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200705_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics', verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=bootcamp.storagemanager.GoogleCloudStorage(), upload_to='resumes', verbose_name='Resume'),
        ),
    ]
