# Generated by Django 3.0.6 on 2020-05-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='content',
        ),
        migrations.AddField(
            model_name='research',
            name='description',
            field=models.TextField(default='', max_length=280),
        ),
        migrations.AddField(
            model_name='research',
            name='link',
            field=models.TextField(default='', max_length=280),
        ),
        migrations.AddField(
            model_name='research',
            name='title',
            field=models.TextField(default='', max_length=280),
        ),
    ]
