# Generated by Django 3.0.6 on 2020-05-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20200520_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='content',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
