# Generated by Django 3.0.6 on 2020-05-31 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0006_remove_research_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='attended',
            field=models.ManyToManyField(blank=True, related_name='attended_research', to=settings.AUTH_USER_MODEL),
        ),
    ]
