# Generated by Django 3.0.6 on 2020-05-31 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(default='', max_length=1000)),
                ('reply', models.BooleanField(default=False, verbose_name='Is a reply?')),
                ('meta_url', models.CharField(max_length=2048, null=True)),
                ('meta_type', models.CharField(max_length=255, null=True)),
                ('meta_title', models.CharField(max_length=255, null=True)),
                ('meta_description', models.TextField(max_length=255, null=True)),
                ('meta_image', models.CharField(max_length=255, null=True)),
                ('liked', models.ManyToManyField(blank=True, related_name='liked_favorites', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='favorites.Favorites')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher3', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorites',
                'verbose_name_plural': 'Favorites',
                'ordering': ('-timestamp',),
            },
        ),
    ]
